initialDir          = /sphenix/user/tmengel/Dijets-AuAu-PPG14/condor/hadding
Universe            = vanilla
Executable          = $(initialDir)/hadding.sh
PeriodicHold        = (NumJobStarts>=1 && JobStatus == 1)
request_memory      = 2GB
batch_name          = overlay_jet20
argList             = $(initialDir)/lists/$(batch_name)_args.list
Output              = $(initialDir)/logs/$(batch_name)-$(PROCESS).out
Error               = $(initialDir)/logs/$(batch_name)-$(PROCESS).err
Log                 = /tmp/condorjob-tmengel.log
Arguments           = "$(file) $(batch_name)"
Queue file from $(argList)
