initialDir          = /sphenix/user/tmengel/Dijets-AuAu-PPG14/condor/overlay_jet10
Universe            = vanilla
Executable          = $(initialDir)/overlay_jet10.sh
PeriodicHold        = (NumJobStarts>=1 && JobStatus == 1)
request_memory      = 4GB
batch_name          = overlay_jet10
Output              = $(initialDir)/logs/$(PROCESS).out
Error               = $(initialDir)/logs/$(PROCESS).err
Log                 = /tmp/condorjob-tmengel.log
Arguments           = "$(PROCESS)"
Queue 5000
