initialDir          = /sphenix/user/tmengel/Dijets-AuAu-PPG14/condor/hijing
Universe            = vanilla
Executable          = $(initialDir)/hijing.sh
PeriodicHold        = (NumJobStarts>=1 && JobStatus == 1)
request_memory      = 4GB
batch_name          = hijing
Output              = $(initialDir)/logs/$(PROCESS).out
Error               = $(initialDir)/logs/$(PROCESS).err
Log                 = /tmp/condorjob-tmengel.log
Arguments           = "$(PROCESS)"
Queue 3000
